import numpy as np

# List of questions
questions = [
    "Have you been feeling depressed or sad lately?",
    "Do you often feel overwhelmed or anxious?",
    "Have you been experiencing difficulty sleeping or eating?",
    "Do you find yourself isolating yourself from others?",
    "Have you been having thoughts of harming yourself or others?",
    
    "Do you have any unhealthy coping mechanisms, such as substance abuse or excessive gambling?",
    "Do you engage in any self-harm behaviors?",
    "Have you tried talking to someone about your feelings?",
    "Do you practice any stress-relief techniques, such as meditation or exercise?",
    
    "Do you have a strong support system of friends and family?",
    "Do you feel comfortable talking to someone about your mental health concerns?",
    "Have you considered seeking professional help from a therapist or counselor?",
    
    "Do you often feel good about yourself?",
    "Do you believe you are capable of achieving your goals?",
    "Have you been experiencing feelings of inadequacy or worthlessness?",
    
    "Do you have healthy and supportive relationships?",
    "Are you able to express your feelings openly and honestly?",
    "Have you been experiencing conflict or difficulties in your relationships?",
    
    "Have you experienced any traumatic events in your life?",
    "Do you struggle with flashbacks or nightmares?",
    "Have you been feeling overwhelmed or stressed by recent events?",
    
    "Do you use any substances, such as alcohol or drugs?",
    "Have you noticed any negative consequences from your substance use?",
    "Have you considered seeking help for substance abuse?",
    "Have you noticed any changes in your mood over the last few days?"
"Have you noticed any changes in your sleep patterns?",
"Have you noticed any changes in your eating habits?",
"Do you feel more tired than usual?",
"How many close friends do you have?",
"Do you enjoy going to work/school/college?",
"Do you get distracted easily when working on something for a long time?",
"Do you often feel tired, worried, or stressed?",
"Are you aware of your emotions as you experience them?",
"Do you seek out activities that you enjoy?",
"Do you feel you have control over your emotions?",
"How many hobbies do you have?",
"How often do you engage in the activities that you like?",
"Do you often spend a lot of time thinking about things that happen to you?",
"Does your mood often go up and down?",
"Are you lively?",
"Do you often worry about things you should not have done or said?",
"Do you get irritated easily?",
"Are your feelings easily hurt?",
"Have you ever engaged in using alcohol or cigarettes after feeling hurt or sad?",
"How often do you feel ‘fed up’?",
"Are you always troubled about feelings of guilt?",
"How often do you feel nervous?",
"Do you worry that awful things might happen to you in the future?",
"Do you worry about your health?",
"Do you like mixing with people?",
"Do you feel life is dull or boring?",
"Do you think people are trying to avoid you?",
"Do you often feel lonely?",
"Do you experience difficulty in starting or completing daily tasks?",
"Have you withdrawn from social interactions or avoided people lately?",
"Do you find yourself feeling restless, fidgety, or unable to stay still?",
"Have you been feeling more irritable or easily frustrated than usual?",
"Do you often feel overwhelmed by your emotions or unable to control them?",
"Have you lost interest or pleasure in activities you used to enjoy?",
"Do you feel hopeless about the future?",
"Do you find yourself overthinking or worrying excessively about small things?",
"Have you had any thoughts of harming yourself or feeling that life is meaningless?",
"Do you ever feel like people are watching you or talking about you when they aren’t?",
"Have you experienced hearing voices or seeing things others don’t?",
"Do you feel disconnected from reality or like you are in a dream-like state sometimes?",
"Have you been struggling with memory, such as forgetting appointments or important details?",
"Do you have difficulty focusing on tasks or conversations?",
"Have you been making impulsive decisions that you later regret?",
"Do you feel mentally exhausted even after getting enough rest?",
"Do you feel like your thoughts are slower or harder to organize than before?",
"Have you been neglecting your personal hygiene or self-care lately?",
"Do you find it difficult to maintain eye contact during conversations?",
"Have others commented that you seem less expressive or emotionally distant?",
"Do you feel like your movements have become noticeably slower?",
"Have you been avoiding certain places or activities due to fear or discomfort?",
"Do you frequently experience sudden mood swings without a clear reason?",
"Have you felt emotionally numb or disconnected from your surroundings?",
"Do you feel like your emotions don’t match what’s happening around you? (e.g., laughing in serious situations)",
"Do you feel anxious when there’s no clear reason to be?",
"Have your thoughts been racing so fast that they’re hard to keep up with?",
"Do you often feel like you’re repeating the same thoughts over and over?",
"Have you been experiencing unusual or irrational fears that interfere with your daily life?",
"Do you sometimes feel like your thoughts are being controlled by an external force?",
"Have you been struggling to find the right words while speaking?",
"Do you frequently misplace things or forget where you have kept them?",
"Have you had trouble making even simple decisions lately?",
"Have you felt like time is moving either too fast or too slow lately?",
"Have you noticed any recent changes in your speech, such as speaking too fast or too slow?",
"Have you experienced difficulty understanding or processing what others are saying?",
"Do you frequently pause mid-conversation because you lose track of your thoughts?",
"Have you caught yourself repeating words or phrases unnecessarily?",
"Do you feel like you understand your current emotional or mental state?",
"Have you been making choices that you later realize were risky or poorly thought out?",
"Do you often regret your decisions soon after making them?",
"Have people told you that your recent behavior seems unusual or out of character?",
"Do you believe you need help with your mental health, or do you feel everything is fine?",
"Do you ever feel confused about where you are or what day it is?",
"Have you found yourself forgetting names of familiar people or places?",
"Do you ever feel like you’re in a different time or place, even when you know logically that you're not?",
"Have you recently experienced moments where you completely lose track of time?",
"Do you sometimes feel like you’re watching yourself from outside your body?",
"Have you been struggling to recall events that happened recently but can easily remember things from years ago?",
"Do you frequently forget what you were just talking about or doing?",
"Have you had difficulty remembering new information, like someone’s name right after they introduce themselves?",
"Have you been relying more on reminders or notes recently because your memory isn’t as sharp as before?",
"Have you ever experienced a sudden gap in memory where you can’t remember what happened for a period of time?",
"Have you noticed yourself becoming unusually suspicious or distrustful of people around you?",
"Do you feel like people are intentionally trying to provoke or manipulate you?",
"Do you struggle to maintain relationships?",
"Have you felt overly dependent on someone for emotional or decision-making support?",
"Do you find it difficult to resist temptations or urges, even when you know they might harm you?",
"Have you had outbursts of anger that you later regretted?",
"Do you frequently interrupt conversations or struggle to wait for your turn to speak?",
"Do you find it difficult to think of solutions when faced with a complex problem?",
"Have you had strong beliefs about being followed, spied on, or targeted without clear evidence?",
"Have you found yourself freezing up or being unable to move during stressful moments?",
"Do you sometimes make repetitive movements (like tapping, rocking, or pacing) without realizing it?",
"Have you been struggling with coordination or balance more than usual?",
"Do you feel overwhelmed by responsibilities?",
"Have you been more sensitive to noise, light, or other sensations lately?"
]

# Convert the list to a numpy array
questions_array = np.array(questions)

def get_random_close_questions():
    questions_array = np.array(questions)
    return np.random.choice(questions_array, 50, replace=False) # Always select 50 questions
